[colors.primary]

background = "#282a36" # {< replace_color(data.colors.background) >}
foreground = "#f8f8f2" # {< replace_color(data.colors.foreground) >}
bright_foreground = "#ffffff"

[colors.cursor]

text = "#282a36" # {< replace_color(data.colors.background) >}
cursor = "#f8f8f2" # {< replace_color(data.colors.foreground) >}

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a" # {< replace_color(data.colors.dim) >}

[colors.normal]

black = "#21222c" # {< replace_color(data.colors.black) >}
red = "#ff5555" # {< replace_color(data.colors.red) >}
green = "#50fa7b" # {< replace_color(data.colors.green) >}
yellow = "#f1fa8c" # {< replace_color(data.colors.yellow) >}
blue = "#bd93f9" # {< replace_color(data.colors.blue) >}
magenta = "#ff79c6" # {< replace_color(data.colors.magenta) >}
cyan = "#8be9fd" # {< replace_color(data.colors.cyan) >}
white = "#f8f8f2" # {< replace_color(data.colors.foreground) >}

[colors.bright]

black = "#6272a4" # {< replace_color(data.colors.hblack) >}
red = "#ff6e6e" # {< replace_color(data.colors.hred) >}
green = "#69ff94" # {< replace_color(data.colors.hgreen) >}
yellow = "#ffffa5" # {< replace_color(data.colors.hyellow) >}
blue = "#d6acff" # {< replace_color(data.colors.hblue) >}
magenta = "#ff92df" # {< replace_color(data.colors.hmagenta) >}
cyan = "#a4ffff" # {< replace_color(data.colors.hcyan) >}
white = "#ffffff" # {< replace_color(data.colors.bright) >}

[colors.search.matches]

foreground = "#44475a" # {< replace_color(data.colors.dim) >}
background = "#50fa7b" # # {< replace_color(data.colors.green) >}

[colors.search.focused_match]

foreground = "#44475a" # {< replace_color(data.colors.dim) >}
background = "#ffb86c" # {< replace_color(data.colors.orange) >}

[colors.footer_bar]

background = "#282a36" # {< replace_color(data.colors.background) >}
foreground = "#f8f8f2" # {< replace_color(data.colors.foreground) >}

[colors.hints.start]

foreground = "#282a36" # {< replace_color(data.colors.background) >}
background = "#f1fa8c" # {< replace_color(data.colors.yellow) >}

[colors.hints.end]

foreground = "#f1fa8c" # {< replace_color(data.colors.yellow) >}
background = "#282a36" # {< replace_color(data.colors.background) >}
