#!/usr/bin/env bash

# Simple alarm clock
# Relies on /usr/bin/at

set -e

trigger() {
    mpv --no-config --scripts="" --loop "$HOME/.local/share/alarm" &

    apid="$!"
    name="${1:-Unknown...}"

    # Show alert
    zenity --info --text="$name" --title="Alarm"
    kill -SIGTERM "$apid"
}

add() {
    if [[ -z "$1" ]]; then
        echo "No time provided"
        exit 1
    fi

    echo "$0 trigger $2" | at "$1"
}

list() {
    for i in $(atq | awk '{ print $1 }'); do
        echo "#$i"
    done
}

prune() {
    for i in $(atq | awk '{ print $1 }'); do
        echo "-> $i"
        atrm "$i"
    done
}

usage() {
    cat <<EOF
Trigger Alarms

Usage: alarm [options]

Options:
  add/set        add an alarm
  prune/clear    prune all active alarms
  list/ls        list all alarms
  trigger        trigger an alarm
  help           display help
EOF
}

case $1 in
    add | set) add "$2" "$3" ;;
    prune | clear) prune ;;
    list | ls ) list ;;
    trigger) trigger "$2" ;;

    *)
        usage
        exit 1
    ;;
esac

