#!/usr/bin/env bash

# Lock theme for swaylock
# https://git.sr.ht/~mvforell/swaylock

font="Terminess Nerd Font"

bg="#000000" # {< replace_color(data.colors.wallpaper) >}
fg="#333333" # {< replace_color(data.colors.hblack) >}
red="#FF0000" # {< replace_color(data.colors.red) >}

swaylock \
    --color "$bg" \
    --ignore-empty-password \
    --show-failed-attempts \
    --indicator-caps-lock \
    --bs-hl-color "$red" \
    --caps-lock-bs-hl-color "$red" \
    --caps-lock-key-hl-color "$fg" \
    --key-hl-color "$fg" \
    --font "$font" \
    --font-size 40 \
    --indicator-radius "140" \
    --indicator-thickness "12" \
    --indicator-idle-visible \
    --inside-color "$bg" \
    --inside-clear-color "$bg" \
    --inside-caps-lock-color "$bg" \
    --inside-ver-color "$bg" \
    --inside-wrong-color "$bg" \
    --line-color "$bg" \
    --line-clear-color "$bg" \
    --line-caps-lock-color "$bg" \
    --line-ver-color "$bg" \
    --line-wrong-color "$bg" \
    --line-uses-inside \
    --ring-color "$bg" \
    --ring-clear-color "$bg" \
    --ring-caps-lock-color "$bg" \
    --ring-ver-color "$bg" \
    --ring-wrong-color "$bg" \
    --text-color "$fg" \
    --text-clear-color "$fg" \
    --text-caps-lock-color "$fg" \
    --text-ver-color "$fg" \
    --text-wrong-color "$fg"


