#!/usr/bin/env bash

# Interact with the mpv socket
# https://mpv.io/manual/master/#json-ipc

SOCKET="/tmp/mpv-socket"

parse() {
    read -r out
    msg="$(echo "$out" | jq -r ".error")"

    if [[ "$msg" != "success" ]]; then
        echo "Error -> $msg"
        exit 1
    fi

    exit 0
}

prev() { echo '{ "command": ["seek", -5, "relative"] }' | socat - "$SOCKET" | parse; }
next() { echo '{ "command": ["seek", 5, "relative"] }' | socat - "$SOCKET" | parse; }
pause() { echo '{ "command": ["set_property", "pause", true] }' | socat - "$SOCKET" | parse; }
play() { echo '{ "command": ["set_property", "pause", false] }' | socat - "$SOCKET" | parse; }
toggle() { echo '{ "command": ["cycle", "pause"] }' | socat - "$SOCKET" | parse; }

usage() {
    cat <<EOF
Interact with the mpv ipc

Usage: mpv-cli [options]

Options:
  prev      jump to the previous 5s
  next      jump to the next 5s
  pause     pause the video
  play      play the video
  toggle    toggle pause/play
  help      display help
EOF
}

case $1 in
    prev) prev ;;
    next) next ;;
    pause) pause ;;
    play) play ;;
    toggle) toggle ;;

    *)
        usage
        exit 1
    ;;
esac

