#!/usr/bin/env bash

# Client for ocr-shot
# Copy response from ocr-shot to clipboard

PORT=""
HOST="ocr.hwk929.ca"
PROTOCOL=https

if ! curl "$PROTOCOL://$HOST:$PORT/" > /dev/null; then
    notify-send "ocr-shot" "Server is not live!"
    exit 1
fi

res=$(
    {
        [[ $XDG_CURRENT_DESKTOP == "niri" ]] && grim -g "$(slurp)" - || maim --select
    } | curl --request POST \
        --url "$PROTOCOL://$HOST:$PORT/" \
        --header "Content-Type: multipart/form-data" \
        --form "file=@-"
)

if [[ "$(echo "$res" | jq .status)" -ne 200 ]]; then
    notify-send "ocr-shot" "Server error - $(echo "$res" | jq .message)"
    exit 1
fi

if [[ $XDG_CURRENT_DESKTOP == "niri" ]]
    then echo "$res" | jq -r .message | wl-copy
    else echo "$res" | jq -r .message | xclip -selection c
fi

