#!/usr/bin/env bash

# Toggle pi.hole DNS
# chatter +/-i for VPNs and such

DNS="192.168.0.5"

reload() {
    systemctl restart NetworkManager

    sleep 1 # stupid hack
    echo

    cat /etc/resolv.conf
}

wipe() {
    chattr -i /etc/resolv.conf
    truncate -s 0 /etc/resolv.conf
}

enable() {
    echo "Enabling pi.hole..."; wipe
    echo "# pi.hole" >> /etc/resolv.conf
    echo "nameserver $DNS" >> /etc/resolv.conf

    chattr +i /etc/resolv.conf
    reload

    exit 0
}

disable() {
    echo "Disabling pi.hole and reverting to defaults..."

    wipe
    reload

    exit 0
}

status() {
    grep "$DNS" /etc/resolv.conf > /dev/null
    exit $!
}

alive() {
    ping -c 1 "$DNS" > /dev/null
    exit $!
}

usage() {
    cat <<EOF
Manage pi.hole DNS

Usage: pihole [enable/disable/status/ping]

Options:
  enable    enable the pi.hole DNS
  disable   disable the pi.hole DNS
  status    check if pi.hole DNS is set
  alive     check if pi.hole is alive
  help      display help
EOF
}


# Parse arguments
case $1 in
    enable)
        [[ "$EUID" == 0 ]] || exec sudo -s "$0" "$@"
        enable
    ;;

    disable)
        [[ "$EUID" == 0 ]] || exec sudo -s "$0" "$@"
        disable
    ;;

    status) status ;;
    alive) alive ;;

    *)
        usage
        exit 1
    ;;
esac

