#!/usr/bin/env bash

# Hotfix because I don't want to have system wide symlinks that point to my home directory.
# This is using:
#  - https://github.com/canonical/lightdm
#  - https://github.com/JezerM/web-greeter

# Copy config
sudo cp ~/.config/lightdm/web-greeter.yml /etc/lightdm/web-greeter.yml
sudo cp ~/.config/lightdm/lightdm.conf /etc/lightdm/lightdm.conf

# Copy theme
sudo cp -r ~/.config/lightdm/hwk /usr/share/web-greeter/themes

